version: '3.8'

services:
  app:
    container_name: meu-pet-feliz
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
